name: Winston Fallback Chatbot
skillMetadata:
  sections:
    - name: Select a Chatbot
      fields:
        - type: select
          name: chatbot_brain
          label: Chatbot Name
          options: Winston|Winston;Alice|Alice;Anna|Anna;AnnaL|AnnaL
          value: Winston
        - type: checkbox
          name: enabled
          label: Enable chatbot as fallback skill
          value: "false"
